# Uncomment this line to define a global platform for your project
workspace ’XYEasyCarousel.xcworkspace'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
# Uncomment this line if you're using Swift
# use_frameworks!

def pods
    pod 'SDWebImage', '~> 3.7.5'             # 网络图片缓存框架
end

target 'XYEasyCarousel' do
    pods
end

target 'XYEasyCarouselTests’ do

end

